# Generated by Django 3.2.5 on 2021-08-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category_specification',
            name='specification_id',
        ),
        migrations.RemoveField(
            model_name='sub_category_specification',
            name='sub_category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_specification_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
        migrations.DeleteModel(
            name='Sub_category_specification',
        ),
    ]
