# Generated by Django 3.2.5 on 2021-08-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210813_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_detail_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
