# Generated by Django 3.2.5 on 2021-08-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
